### ISSUE TITLE
Can't access original file

### ISSUE THREAD

**Issue by fred1337** [danielquinn/paperless#113]
Hello,

I keep getting this error when it finished scanning file. I just can't access the original file in the admin page. Did I miss something in the configuration file ?
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/src/../media/documents/originals/0000012.pdf.gpg'`

**Comment by danielquinn** [comment]
It's tough to know what's going on with just the last line of the backtrace.  Typically if something blows up, you get a lot more error output to get an idea of what broke where.

Is this output from the consumer or the webserver?  With an error like that, my guess is that the consumer tried to write the encrypted PDF to the media directory when it was finished indexing, and failed -- for some reason -- probably permissions on the directory?

**Comment by fred1337** [comment]
It's from the consumer 
here is the full tracebck
`Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 55, in handle
    self.loop()
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 65, in loop
    self.file_consumer.consume()
  File "/usr/src/paperless/src/documents/consumer.py", line 129, in consume
    document = self._store(self._get_ocr(imgs), doc, thumbnail)
  File "/usr/src/paperless/src/documents/consumer.py", line 316, in _store
    with open(document.source_path, "wb") as encrypted:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/src/../media/documents/originals/0000013.pdf.gpg'
`
Yeah I guess it's permissions issue but it's the first time I use Docker and I can't get my hand on the "media" folder.

**Comment by danielquinn** [comment]
So what appears to be happening is that the consumer finds the file to consume, does the OCR stuff and then tries to save an encrypted copy of the original PDF in the `media` directory under `documents/originals`.  At this point it fails because of a `FileNotFoundError`, so the whole thing doesn't get stored and that's why you don't see it in the UI.

That's definitely weird.  It doesn't look like permissions so much as a missing path -- which is weird, because that path (`media/documents/originals/`) is part of the git repo.  I know that the Docker instance works for other people, and that nothing has changed in this area for some time so I'm left asking about your process.

Can you walk me through just what you did to arrive at this error?  As in, (a) have you managed to store other documents in Paperless, or is this the first one? (b) How did you set things up?  Did you do a `git pull` and then follow the [Docker instructions](http://paperless.readthedocs.org/en/latest/setup.html#docker-method), or download a zip and not look at the docs? etc etc.

**Comment by xsteadfastx** [comment]
i step into the same error with docker. strange. permissions are fine.

**Comment by xsteadfastx** [comment]
do i have to git pull first? because the docker-compose file pulls a prebuilt image from docker hub? i just used that.

**Comment by xsteadfastx** [comment]
thats it. i use local folders for data and media as docker volumes... and so `media/documents/originals/` and `media/documents/thumbnails/` doesnt exist.
