### ISSUE TITLE
Service fails to start (systemd)

### ISSUE THREAD

**Issue by davidtorcivia** [danielquinn/paperless#123]
Hey all,

I'm hesitant to post this here as I'm sure it's user error and not a paperless bug, but figured I'd reach out for thoughts. 

First off, thanks for paperless it's a great piece of software and I really appreciate the time all of you put into it.

Now, I've got it all installed and working great on my local server (already tried scanning to it and successfully converting documents, tagging, etc and it works perfectly).

I'm currently trying to add it the autostart files to systemd (Ubuntu 15.04 which is systemd) and I can't seem to get it to start. I've checked the scripts and they seem correct, but the server won't start except when I manually `$ ./manage.py runserver ip:port`. Systemctl scripts below:

     [Unit]
     Description=Paperless webserver
     
     [Service]
     User=paperless
     Group=paperless
     ExecStart=/usr/bin/python3 /var/www/html/myserver/paperless/src/manage.py runserver myip:myport
     
     [Install]
     WantedBy=multi-user.target

and

     [Unit]
     Description=Paperless consumer
     
     [Service]
     User=paperless
     Group=paperless
     ExecStart=/usr/bin/python3 /var/www/html/myserver/paperless/src/manage.py document_consumer
     
     [Install]
     WantedBy=multi-user.target

I've got a paperless user and group with read/write permissions in the paperless directories (tested and confirmed this). That's the correct directory for python3 and manage.py.

I've checked the systemctl log with 

`$ sudo systemctl status paperless-webserver.service`

which shows me that the error is 

`python3[1858]: ImportError: No  module named 'django'` 

which is the same error I get when I check for django version using 

`$ python -c "import django; print(django.get_version())"`

 while 

`$ python3 -c "import django; print(django.get_version())"` 

gives me the proper version info (1.9.4).

However, my .service is definitely calling python3, but just in case I tried calling python and python3.4 and still encounter the same error when restarting the service (while putting an incorrect path to python just causes a generic fail and exit).

Puzzled because it works when I manually call execute everything, just not with systemd. Any insight would be very much appreciated!

**Comment by danielquinn** [comment]
In your `.service` files, you're explicitly invoking `/usr/bin/python3` and not `/path/to/virtualenv/bin/python` which makes me think that you're either (a) not using a virtualenv, (b) aren't referencing the right python library, or (c) haven't figured out that there's a difference.  To be fair, the way virtualenv overrides your $PATH variable does make it difficult to know what's going on sometimes.

It looks like while your system definitely has python 3 available, perhaps you've installed Django (and the rest of Paperless' dependencies into a virtualenv (as is suggested in the documentation).  If that's the case, you can't invoke `/usr/bin/python3 /path/to/manage.py` because you'll be calling the *system* Python and not the Python in your virtualenv.  If I'm correct, and you did install everything with virtualenv, then you'll want to invoke it with:

    /path/to/virtualenv/bin/python /path/to/manage.py runserver 0.0.0.0:8000

(note that when you invoke a specific `python` instance from a virtualenv, you can be sure of the version, so `python` is just a symlink to `python3` in this case.

Remember also that running things in a virtualenv means overwriting your `$PATH` variable.  In other words, once you're in a virtualenv, `python` will exectue to `/path/to/virtualenv/bin/python` while running `python` in another window (that hasn't invoked `/path/to/virtualenv/bin/activate` yet) will get you `/usr/bin/python`.

If you're not using a virtualenv (and you should be), then the problem may be that you haven't installed all of the dependencies system-wide.  I don't recommend this, but you could theoretically run the following as root:

    # pip3 install /path/to/requirements.txt

That will install all of Paperless' requirements system-wide, but will also **overwrite and/or interfere with your system-level package management system** like apt/dfn/pacman/emerge.  Theoreticall, you can also do something like:

    $ pip3 install --user /path/to/requirements.txt

...which would install the libraries user-wide, but I'm not sure how that would work.
