### ISSUE TITLE
Gitter chat

### ISSUE THREAD

**Issue by jat255** [danielquinn/paperless#13]
This looks like a great project. I'm working on getting it setup on one of my home servers, but have run into a couple questions. Is there (or should there be) a [gitter chat](https://gitter.im/) for the project, or maybe and IRC channel? That could help get new users into the swing of things a little easier.

**Comment by danielquinn** [comment]
Heh.  I don't have anywhere near the time to maintain something like that, and for some reason, I can't even connect to Freenode right now, so I think if you've got questions, the best thing to do would be to open a ticket along the lines of something like "the documentation doesn't explain what to do when X" and I'll help you there *and* fix the docs at the same time :-)

**Comment by jat255** [comment]
Yeah, maybe the IRC is a bit much, but the gitter chat is really just a couple of clicks to get it set up, and then a little badge goes into the Readme. Doesn't really take any maintenance at all. We use it quite successfully on one of the [repos](https://gitter.im/hyperspy/hyperspy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) I contribute to. Obviously, up to you.

My specific question had to do with the `PASSPHRASE` variable. It's unclear from the documentation what it does, or what it should be set to? Is this the passphrase for your gpg key? The only place it's mentioned is in the docs is on the [Setup](https://paperless.readthedocs.org/en/latest/setup.html?highlight=passphrase) page, and that just tells you set the value (but not what to set it to :smile:).

**Comment by danielquinn** [comment]
Heh.  Alright, I'll have a look at the docs for that.

Basically, the `PASSPHRASE` variable is used during consumption and later for downloading original documents:

* During consumption, paperless uses gpg to encrypt the original document and save it to `<MEDIA_ROOT>/documents/pdf/<id>.pdf.gpg`.
* Later, via the admin, you can click on the little PDF icon and it'll then transparently decrypt the file from that location and stream it back to you.

The encryption is using symmetric=True, so we're not using public/private key stuff here (as the sender and recipient are the same).

So, if you set the passphrase in the `settings.py` file, you're good to go.  Otherwise, you have to set `PAPERLESS_PASSPHRASE=super-secret-key` in the environment.  If the passphrase is blank, I'm not sure what will happen.  You may get a zero-byte encrypted file?

As for gitter chat, I'm on a train right now on my way to Brussels for [FOSDEM](http://fosdem.org/), but I'll give it a shot so long as my wifi tether holds up.

**Comment by danielquinn** [comment]
Ok, the gitter chat thing is setup, so I'm going to close this one, but I'll try to remember to fix the docs to better define the passphrase stuff :-)
