### ISSUE TITLE
webserver cpu load in idle

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#132]
I recognized that the webserver without the consumer script always consumes about 10% and often more cpu load.
What is running in background?

**Comment by danielquinn** [comment]
The webserver isn't doing much, but then again, it's not a proper webserver.  Paperless is abusing the Django development server, which does what it can to monitor files that make up the project so that if anything changes, it can be rebooted in real time.

A proper Django project is usually hosted with Gunicorn under Nginx or Apache, which are much better at this job than Python, so you'd probably save a lot of resources there.

**Comment by Ulli2k** [comment]
Is it easily possible to get paperless running on apache? I already have apache running in parallel...

**Comment by danielquinn** [comment]
It should be.  I haven't bothered with it since I run Paperless locally on port 8000 while I run Nginx on port 80 for public stuff.  But if you want to install it as a VirtualHost it shouldn't be too tough, just follow [the instructions on the Django website](https://docs.djangoproject.com/en/1.9/howto/deployment/wsgi/modwsgi/) for deploying a standard Django application.

If you come out of it with anything handy that you think could be used, feel free to submit a PR.

**Comment by avichalp** [comment]
Would it be a good idea to include a gunicorn config file in the project so the user can choose between running a django management server and running gunicorn server ?

**Comment by danielquinn** [comment]
Definitely, yes.  I just use the runserver on my setup, but if you've got a working gunicorn config, then by all means, pop it into the `scripts` directory and send me a PR :-)

**Comment by avichalp** [comment]
Sure. I will submit a PR.

**Comment by avichalp** [comment]
@danielquinn here is the [PR] (https://github.com/danielquinn/paperless/pull/156)

**Comment by danielquinn** [comment]
#156 has been accepted now.  Does this mean I can close this issue, or do you guys wanna try it out first?

**Comment by AlmightyFrog** [comment]
Same problem still exists here, for me it is about 5 to 20% on idle on an atom cpu.
Can someone please tell me how to use the gunicorn.conf correctly within docker deployment?
Then i could tell, if problem is solved or not.

**Comment by erikarvstedt** [comment]
This issue has been fixed with #328.

**Comment by danielquinn** [comment]
Good point @erikarvstedt.  Closing now.
