### ISSUE TITLE
Add requires.io

### ISSUE THREAD

**Issue by JamieMagee** [danielquinn/paperless#138]
[requires.io](https://requires.io/) monitors dependencies, and allows you to see at a glance if any of your dependencies are out of date. It's how I caught #137

**Comment by danielquinn** [comment]
I'm not sold on requires.io, in part because it keeps asking me for more and more permissions.  When I tried to set it up, it asked for write permissions (to webhooks only) for *all* of my repos with *all* of my organisations and after that, in order to send PR's it wanted additional credentials (though it was unclear to me what exactly it wanted).

When I can just run `pip list --outdated` from time to time, I don't really see the value in requires.io.

**Comment by JamieMagee** [comment]
Fair enough. In that case, can I suggest an alternative - [VersionEye](https://www.versioneye.com/). It only requires read access to public repos, and read access to your email address (for dependency update notifications)

**Comment by danielquinn** [comment]
I'll check it out, thanks.  I'll post back here when I work something out.

**Comment by danielquinn** [comment]
The badge for Versioneyes is uglier, but they allowed me to add the project via a URL rather than granting any GitHub permissions, so I call that a win.  The badge is now in the README.  Thanks for the suggestion!

**Comment by JamieMagee** [comment]
Thanks for the update. I'll close this issue.

**Comment by danielquinn** [comment]
Just a quick note: I had to downgrade Django to 1.9.8 temporarily while I figured out why everything was breaking on me.  It turns out that all of my code was fine, and I wasn't using anything deprecated, but actually it was django-rest-framework that needed to be upgraded along with Django.  I've since updated both and we're back up to 1.10.  I hope that didn't break anything for you.
