### ISSUE TITLE
Document Views are insecure

### ISSUE THREAD

**Issue by jbogatay** [danielquinn/paperless#146]
the /fetch endpoint is unsecured.   Pull incoming.

**Comment by thomasbrueggemann** [comment]
@jbogatay The only problem is now, that it is not possible to fetch the thumbnail/document via the REST API. What do you think?

**Comment by danielquinn** [comment]
Can't you just hit the URL listed in the API?  So long as you're logged in, the fetch should work.

**Comment by danielquinn** [comment]
Sorry, for clarification: BasicAuth should be supported, so hitting those URLs with `http://user:password@domain.tld/path/to/document` should do the job.

**Comment by danielquinn** [comment]
Nevermind, I see the problem now.  `FetchView` is a custom view rather than a subset of DjangoRestFramework's views, so BasicAuth isn't supported there.  Truth be told, I never imagined using Paperless without logging in first, so I didn't test for this.

@thomasbrueggemann if this is important to you, you should probably open a separate issue so we can work things out there without harassing @jbogatay in this thread.

**Comment by thomasbrueggemann** [comment]
Sounds fair! I think paperless as a standalone API server is quite the powerful tool to build upon.
Switching over to #178
