### ISSUE TITLE
Single page documents only?

### ISSUE THREAD

**Issue by denysvitali** [danielquinn/paperless#151]
Hi everyone,
thanks for creating this awesome project.

I do have already worked with a cool (paid, M$ based and closed source) Document Manager System named [DocuWare](http://docuware.com/).
I've felt like this was the right project to contribute to, since we (meaning in the OSS community) don't have any software like this.

I literally bought a scanner because of this project, I'm having troubles on saving all my papers around the house. I hate those letters that you legally have to keep for some reason (warranties, receipts and so on).
I've seen the project now supports only PDFs as a "multiple page input", and was wondering how you think the multi pages documents are going to be integrated.
In my experience, merging and reordering PDF pages is really, really tricky - unless you use some closed source software (like Adobe Acrobat DC, which isn't free).

How have you guys planned to keep multiple (maybe TIFF) pages in this document manager system?
Anyways, as soon as I have more free time I am really gonna contribute to this project because it deserves a nicer interface / more features and also because I really need it :D

**Comment by danielquinn** [comment]
Actually, operating on PDFs is easy in Free software land.  My go-to tool is [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/).  You can splice out pages, re-order them, lots of cool stuff.

In terms of supporting saving documents as multi-image groups, that's not currently in the pipeline and unless someone else takes it on, I'm not likely to implement it.  Given the way stuff is consumed, I would think you'd have some sort of Paperless standard of "images named sequentially in a tarball" or something like that.  Because of the way we store documents (document id + file extension) I wouldn't want to start storing multiple files per document.

**Comment by denysvitali** [comment]
Great, it was just to better understand how you wanted the system to work.
I'll fix my scripts accordingly :+1:
