### ISSUE TITLE
CSS/JS not found when using Docker

### ISSUE THREAD

**Issue by jmjordan** [danielquinn/paperless#167]
I've setup paperless using Docker on OS X. Everything is working except for the static files. I get a 404 for all CSS and JS.

I tried running `./manage.py collectstatic` but that did not fix the issue.

**Comment by jmjordan** [comment]
After a bit more poking I fixed the problem.

I added the following to Dockerfile after `RUN ./manage.py migrate`:

    RUN ./manage.py collectstatic --no-input

After that I rebuilt the docker image with `docker build .` and used the resulting image in docker-compose.yaml.

I will work on creating a pull request.

**Comment by pyle** [comment]
Thanks @jmjordan that fix worked for me also. Did you already have a PR going? If not I can put one forward.

**Comment by dennis-tra** [comment]
This fixed it for me too. Thank you. The image on docker hub still has this issue.

The fix isn't merged to yet.

**Comment by danielquinn** [comment]
The docker image is maintained by @pitkley but I haven't seen him post here for a while so he might just be super busy.  If all that's required is a triggering of the build for Docker Hub, then maybe my mentioning him here will get his attention ;-)

**Comment by pitkley** [comment]
@danielquinn thanks for the mention, @dennis-tra I'll try and look into it within the next 24 hours :+1:

**Comment by pitkley** [comment]
Okay, I have looked into it @dennis-tra. I was surprised reading here that you had issues with the image on Docker Hub, since I am using it without issues on my end.

Turns out: I am [disabling](https://github.com/pitkley/docker-paperless/blob/f505a88fd64d16d2987184cd853b2cc1aed9de09/Dockerfile#L18) the `DEBUG` setting in the image to not expose Djangos debug capabilities to potentially the world without authentication in case of an error. But disabling `DEBUG` also stops serving static files.

If you want `DEBUG` disabled but still serve static files using the built-in server, you have to supply the [`--insecure`](https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#cmdoption-runserver-insecure) flag to the `run`-command:

```yaml
command: ["runserver", "--insecure", "0.0.0.0:8000"]
```

The best solution would be to use a server like nginx to serve the static files, but I currently do not have the time on my hands to modify the compose-stack and the `Dockerfile` to make that possible.

So the solution right now is to [add the `--insecure` flag](https://github.com/pitkley/docker-paperless/blob/e94dba9e5173cdd074a3e6a57355df3df4da621c/docker-compose.yml.example#L20) to the `webserver`. While it might sound bad, it actually is more secure than running with `DEBUG` enabled.

----

If your installation of Paperless is not public-facing and you require `DEBUG` to be enabled, feel free to open a pull request to the [repo](https://github.com/pitkley/docker-paperless) that feeds into Docker Hub and make the `DEBUG` setting configurable -- or even better, open a pull request to *this* repository and make the `DEBUG` setting configurable for Paperless as a whole! 😃

**Comment by dennis-tra** [comment]
Thanks @pitkley for your efforts in finding the problem. My paperless installation is not public facing and I'll try out your suggestions! Have a good day :)
