### ISSUE TITLE
Directories required by paperless

### ISSUE THREAD

**Issue by nigelm** [danielquinn/paperless#169]
Paperless requires some directories to be in place, and currently fails with a somewhat unclear traceback (permissions issues) if they are not in place.

It may be worth adding these to a documentation checklist, configuration file example, or improving the error message if they are missing.

The directories I am aware of that cause tracebacks are:-

- *PAPERLESS_DBDIR* - also should change the conf example to not end with `file`
- *PAPERLESS_MEDIADIR*`/documents/originals`
- *PAPERLESS_MEDIADIR*`/documents/thumbnails`

I'll look at putting a pull request for these when I get a chance.

**Comment by danielquinn** [comment]
I guess because I just stick to the defaults, I never saw this, but you're right, there should be a check run as part of the [system check framework](https://docs.djangoproject.com/en/dev/ref/checks/) so if you're planning on a PR, by all means, please use that.  Regardless, I'll mark this as a bug so I'll remember to get to it if you don't.

**Comment by danielquinn** [comment]
I've just pushed some changes to master that include some checks to find problems like this.  Please let me know if you find these sufficient, and re-open this issue if necessary.

**Comment by nigelm** [comment]
Confirmed fixed
