### ISSUE TITLE
Dynamic Secret Key Base

### ISSUE THREAD

**Issue by dopykuh** [danielquinn/paperless#171]
Hiho, you're setting the secret key statically, it would be nice to load them from environment or config.
https://github.com/danielquinn/paperless/blob/master/src/paperless/settings.py#L25

**Comment by danielquinn** [comment]
You know, I never considered putting a Paperless inflation on the open web, so the secret key never seemed all that important, but you're right, it should be configurable. 

If you'd like to offer a pull request that follows the same pattern as the other configurable variables, I'll merge it.  Otherwise I'll add it to the queue of small things to add when I have time.
