### ISSUE TITLE
Possible to specify ALLOWED_HOSTS in paperless.conf?

### ISSUE THREAD

**Issue by ekw** [danielquinn/paperless#172]
My paperless installation doesn't run unless I add my hostname to ALLOWED_HOSTS in 'src/paperless/settings.py'.  Rather than modifying that source file, can I specify it in '/etc/paperless.conf' instead?  Since settings.py has load_dotenv("/etc/paperless.conf") statement in it, I tried putting these (and probably a few more variations) in /etc/paperless.conf with no success:
```
ALLOWED_HOSTS=['my_hostname']
ALLOWED_HOSTS='my_hostname'
ALLOWED_HOSTS=my_hostname
PAPERLESS_ALLOWED_HOSTS=['my_hostname']
PAPERLESS_ALLOWED_HOSTS='my_hostname'
PAPERLESS_ALLOWED_HOSTS=my_hostname
```
Do I just not have the correct syntax or is this not possible?  Thanks.

**Comment by danielquinn** [comment]
ALLOWED_HOSTS is only necessary if you're putting Paperless in a public environment and intend to turn `DEBUG` off.  You can set it, but since I never intended Paperless to go on a public machine, I haven't prepared the code for that.

The problem you're having is that if you set `ALLOWED_HOSTS=os.getenv("PAPERLESS_ALLOWED_HOSTS")` what you're telling Python is to set `ALLOWED_HOSTS` to the *string* value of whatever is in `${PAPERLESS_ALLOWED_HOSTS}`.  Since Django expects this variable to be a list, that will never work.

So in other words, you're actually doing this:

```python
ALLOWED_HOSTS="['my_hostname']"
```

The work-around for this is kind of a pain in the ass because of how Python works, but it would look something like this:

```bash
# /etc/paperless.conf
PAPERLESS_ALLOWED_HOSTS=example.com
```

```python
ALLOWED_HOSTS = []

allowed_hosts = os.getenv("PAPERLESS_ALLOWED_HOSTS")
if allowed_hosts:
    ALLOWED_HOSTS = allowed_hosts.split(",")
```

This would allow you to not define PAPERLESS_ALLOWED_HOSTS, or do stuff like this:

```bash
# /etc/paperless.conf
PAPERLESS_ALLOWED_HOSTS=example.com
```

or

```bash
# /etc/paperless.conf
PAPERLESS_ALLOWED_HOSTS=example.com,example.net
```

Either that, or I could just hard-code this:

```python
ALLOWED_HOSTS=["*"]
```

Which is very bad form and not at all secure, but it would work for everyone should they choose to put this publicly somewhere.

In short, none of these options are very good.  Can I ask, why are you needing to set ALLOWED_HOSTS at all?  Are you actually putting a Paperless instance on the public internet?

**Comment by ekw** [comment]
No, I'm not putting Paperless on the public internet and don't plan to, but I can get to the VM I'm running it on via LAN by using http://paperless.home in the browser.  Without specifying this hostname in ALLOWED_HOSTS, I get a Django error.  Have you just been using the local IP address to get to Paperless?

This code you provided works perfectly though and just what I was looking for:

> ```
> ALLOWED_HOSTS = []
> 
> allowed_hosts = os.getenv("PAPERLESS_ALLOWED_HOSTS")
> if allowed_hosts:
>     ALLOWED_HOSTS = allowed_hosts.split(",")
> ```

**Comment by danielquinn** [comment]
I think I know what happened.  Along with a recent update, I included a bump from Django 1.10.3 to 1.10.4 which I think changed how ALLOWED_HOSTS is treated.  Until recently, so long as DEBUG was set to `True`, ALLOWED_HOSTS was largely ignored, but that's not happening anymore.

Anyway, I've introduced the changes we talked about here with one exception: the default for ALLOWED_HOSTS is now `["*"]`, since that replicates the original behaviour and Paperless isn't meant to be on the open internet anyway.  I've also included support for someone setting their own ALLOWED_HOSTS value by way of /etc/paperless.conf.  There's an explanation in the example file.

If you've hacked your settings.py file to include the above, you should be able to do this to bring your code base back into line with master:

```bash
git checkout src/paperless/settings.py
git pull
```

**Comment by danielquinn** [comment]
Honestly?  I have no idea.  That's *really* weird, 'cause you're right, `load_dotenv()` is loading the values in `paperless.conf` into the environment.  Code above that shouldn't work unless somehow some other process has previously loaded the environment for you.

Django has a weird trick with his dev server where it runs two instances: one to watch the app for changes, and another to actually run the program.  Perhaps that's what's going on there?  Regardless, I wouldn't expect that to work in a gunicorn-based setup.

**Comment by ekw** [comment]
Yeah, that is strange, but It Works.  Thanks for all your help!  Paperless is an awesome app and I can ditch the horrendous software that came with my scanner now!

I forked your repo and made some changes/customizations, including displaying thumbnails in the admin and using django-suit theme.

Using django-suit is purely cosmetic, but displaying thumbnails really adds to the usability (for me).  I display thumbnails by decrypting and inlining the base64 encoded image, so performance takes a bit of a hit, but I like the thumbnails. Wondering if you see a better way to do this?  One possible optimization I see is to reduce the size of the thumbnails; they are actually quite large for thumbnail images.

I also saw that you were starting on a UI separate from the Django admin.  Is that something you still plan on doing (eventually)?  Or, if you're like me, when things are "good enough", which Paperless is more than at the moment, I consider it done and move on to something else.

**Comment by danielquinn** [comment]
The thumbnail thing is an annoying problem really.  I didn't want to store it unencrypted, so the alternative is basically what you've done there, though I typically would go for modifying serving the image as an image as I've done in the `ui` branch [here](https://github.com/danielquinn/paperless/blob/ui/src/documents/views.py#L34) to return the image to the browser (saves you having to inline the base64 data).  Doing it this way will also help with the server-load, since the browser won't re-request images that have been cached client-side.  Though it'd probably help to add some headers to that view that increase cache time.

As for the `ui` branch, you're right, I had started on writing one, but when I discovered mayan-edms, that kind of took the wind out of my sails.  As you say, Paperless is "good enough" for me right now, but I recognise that there's a lot of people using it, so I try to keep it up to date and merge in the occasional PR that makes sense.  Your use of django-suit and adding the thumbnails though sounds like a no-brainer and something worth merging.  If you're willing to adjust how you've handled the thumbnails to use something closer to what I've mentioned here, I'd be happy to merge your changes as a PR.

**Comment by ekw** [comment]
I wanted to do thumbnails that way in the first place, but I'm not that familliar with Django and didn't see you already provided a url for that.  But I will change how I handle thumbnails and do a PR.

**Comment by danielquinn** [comment]
Cool beans!  Well if you have any questions or just need help with Django, let me know.  I've been hacking on this framework since 2008 :-)

**Comment by ekw** [comment]
OK, I've changed it so thumbnails are no longer inlined: 
https://github.com/ekw/paperless/commit/c5bd3be8767b498d5068d199fcd657f94602953f

But if you look at my commit history, my git/github-fu is not very strong.  I somehow ended up with 2 commits for this thumbnail change and 2 commits when I tried to pull in your new stuff.  I use mercurial, but I heard git can rewrite the commit history.  If you merge my stuff as is, can you fix my amateur hour mistakes?

**Comment by danielquinn** [comment]
Git is a huge pain in the ass, but the more I learn about it, the more I love it.  I know just how you feel :-)

Some projects are super-picky about how you submit a pull request, that there be only one commit, and everything needs to be rebased onto said commit etc.  I don't care about that stuff, so go ahead and issue the pull request.  If there's nothing that needs to be fixed in the code and the tests pass, I'll merge it.
