### ISSUE TITLE
Help customizing templates

### ISSUE THREAD

**Issue by ekw** [danielquinn/paperless#180]
I want to toy around with some admin customizations and want to begin with modifying django-suit's base_site.html per http://django-suit.readthedocs.io/en/develop/configuration.html#templates.  I've copied this base_site.html everywhere I think it might go, but it is not being used.  

I've tried putting base_site.html in:
```
src/documents/templates/admin/
src/documents/templates/admin/documents
src/documents/templates/suit
src/paperless/templates/admin
src/paperless/templates/suit
```

I can override change_list.html by placing it in /src/documents/templates/admin/documents/change_list.html

But cannot figure out where base_site.html should go.  Appreciate any pointers on doing this.

**Comment by danielquinn** [comment]
I'm going to have to stop you right there.

I got an email from one of the Django Suit developers last night who explained to me that the license on Suit is incompatible with Paperless' use of the AGPL.  You see, we're currently using Suit under its free *non-commercial attribution* license, which means that if someone uses Paperless for commercial purposes (entirely likely), we'd be helping them violate the terms of Suit's license and that's not cool.

In response to their email, I'm going to have to remove Suit from requirements.txt and (potentially) re-add it as an optional dependency where we introduce some logic that checks for the module's existence and use it if that's the case.

Regardless of which option I go with, I can't have Paperless be *dependent* on Suit for the above reasons, so modifying the templates in a way that's incompatible with core Django is a non-starter.

So I'm asking you: given the above, would you rather we allow of basic use of Suit only (via some magic code checking for its pre-existence) or would you prefer we standardise on Django core?

For my part I'm thinking we abandon Suit altogether, but I'm open to being convinced otherwise.

**Comment by ekw** [comment]
I don't want to be hamstrung by this, so I'd also rather abandon suit.  Sorry about that, I was aware of the license, but thought we'd be safe with the non-commercial clause, but I guess that's why IANAL.

Are you open to other admin themes that are more free software friendly?  http://grappelliproject.com seems interesting.  According to bottom of its website, it is New BSD license.  I might give that a try.

**Comment by ekw** [comment]
I've removed use of django-suit, but is there still a way to get PAPERLESS_LIST_PER_PAGE from the conf file to set DocumentAdmin.list_per_page in src/documents/admin.py?

**Comment by danielquinn** [comment]
Don't worry about the license mixup.  I wouldn't have merged the commit if I had considered the for-profit applications of this project, so this is on me.  I just have to remove it -- hopefully today if I can find the time.

As for the number per page question, you can adjust the number of elements per page directly in the *Admin classes, so I can make that use PAPERLESS_LIST_PER_PAGE instead without depending on Suit.

As for Grappelli, I'm familiar with it as I've used it on another project.  I can't say that I think it's a great improvement over the default though, so unless there's a feature in there you think would be a big win, I'm inclined to just stick with the default.

**Comment by ekw** [comment]
I already removed django-suit on my fork, so I created a PR.  Yeah, I'm running grappelli on a branch right now and the only thing it offers is marginally better aesthetics.

**Comment by danielquinn** [comment]
Thanks for the PR!  I <3 Free software :-)

Alright then, for now, I'm going to close this issue and keep Grappelli in mind for a potential change in the future.  If you do have template changes you'd like to make that play nice with the default styles (and potentially Grappelli as well) then I'm happy to field them here.

**Comment by ekw** [comment]
> As for the number per page question, you can adjust the number of elements per page directly in the *Admin classes, so I can make that use PAPERLESS_LIST_PER_PAGE instead without depending on Suit.

If you let me know in general terms how to go about this, I can probably do it.  I just don't know the proper Django way to access things in the conf file from the *Admin classes.

**Comment by danielquinn** [comment]
Sorry about not responding to this sooner, this week has been messy.  I'll have another poke at Paperless this weekend at which point I'll add the list-per-page thing.  To be honest, I don't remember exactly where the setting is, so I'd have to look it up myself, but I think it's just a class attribute on the `*Admin` classes or something.  I'll let you know when I fix it :-)
