### ISSUE TITLE
Paperless spam email

### ISSUE THREAD

**Issue by denysvitali** [danielquinn/paperless#192]
Hello everyone,
I'm opening an issue to discuss with you about a recent email I received this morning.
Apparently I've been subscribed to a mailchimp list of a company named "Ambar".

If someone other has received the same email (that starts with "Hello!
Many Paperless users have already gravitated towards Ambar because it’s fast, scalable, (...)" and haven't subscribed to the mailing list, please unsubscribe and report it to mailchimp. This is pure spam.

![screenshot_20170220-114749](https://cloud.githubusercontent.com/assets/4939519/23122166/5b788982-f763-11e6-91f2-ae17f10b0e38.png)

**Comment by danielquinn** [comment]
Wow.  This is a thing now?  I've been getting spam to my code@ account, but it's mostly been from recruiters.  This is a new low.

If there's something I can do to kill this, please let me know.  I haven't yet received any spam like that, but I'll post here if I do.

**Comment by denysvitali** [comment]
The only way to kill it is to receive the mail, Unsubscribe and put as a reason "I never subscribed to this list".
Damn spammers

**Comment by nopjmp** [comment]
They were linking to their product from Reddit as well. This is their username https://www.reddit.com/user/sochix

Thankfully I caught this while I was researching into them vs Paperless. I would rather use Paperless if they are going to be spamming.

**Comment by sochix** [comment]
First of all, I'd like to apologize to all of you for this outrage...

I'm a co-founder and CTO of Ambar.

_I'd like to explain, please:_
Last weeks I've been dedicating all my time to developing the cloud version of Ambar. So I hired a freelancing guy to help us increase traffic to our landing page and do marketing. I let him act on my behalf and didn't control him properly... The worst managerial mistake ever...

I'm deeply sorry for this mess, my sincere apologize to all of you, especially to @danielquinn. It was absolutely inappropriate and it was totally my mistake.

That won't happen again, I told the guy to stop all activities and mailing campaigns.

Now I'm taking over all the marketing stuff and I guarantee you that Ambar will never be spamming anyone.

Thank you and sorry again

**Comment by CapacitorSet** [comment]
I also received the email in question. I suspect it may have been harvested from the stargazers, because the only interaction I had with Paperless so far was starring the repository.

**Comment by denysvitali** [comment]
Wow, they've sent 3k mails then?

**Comment by danielquinn** [comment]
I think we can all agree that this was a dick move by Ambar, and despite the fact that [they still haven't deleted the unkind reddit comment](https://www.reddit.com/r/goingpaperless/comments/5u0oww/who_uses_paperless_can_you_recommend_it/ddz3pdz/) I'm going to close this since I'm assuming that the spamming has stopped.

I guess it's an inevitable result of a project becoming popular.  There's been a lot of action on this sort of thing out there, so I guess I should feel honoured that actual for-profit companies see Paperless as a threat.  I'd much rather just see these groups adopting the project and releasing their updates under the GPL, but maybe I'm just idealistic.

I suppose if this sort of thing happens again, I'll add a *Hall of Shame* section to the README or something, chronicling all the nasty behaviour by companies not playing nice.
