### ISSUE TITLE
Elasticsearch/Lucene/Solr

### ISSUE THREAD

**Issue by cromulus** [danielquinn/paperless#21]
While Postgres does have fantastic fulltext search, might I suggest using a purpose built search engine?

**Comment by danielquinn** [comment]
Actually, the current setup is to use Sqlite because I don't like dependencies for the sake of them.  ElasticSearch & Solr (and Postgres) are all impressive software packages, but for a use-case this small I don't see the value in complicating the process for everyone.

Switching from Sqlite to PostgresSQL or MySQL is easy enough, since that's just changing a few values in the config, so I leave it to the user to do what she likes and depend on whatever there, but introducing a dependency on yet another system-level package to comb through a few hundred blobs of text?  I don't see the point.

Unless you can show me how we could optionally support ElasticSearch, perhaps with a simple config value.  Then I'd be ok with allowing the expansion.  But to depend on it? Absolutely not.

**Comment by cromulus** [comment]
Makes sense. Thanks!
