### ISSUE TITLE
Add thumbnails in export/import scripts

### ISSUE THREAD

**Issue by CkuT** [danielquinn/paperless#218]
Hey !

Unless I'm mistaken, the file thumbnails are not handled in export and import scripts, which results in a bunch of broken images in the django-admin interface.

It would be great if the thumbnails were exported, or at least recalculated during the import process.

What do you think ?

**Comment by danielquinn** [comment]
Yeah that makes perfect sense.  I think this is because the import/export process was written long before the thumbnail part was added.

Ideally we should export the thumbnails with everything else since they're not very big and it would keep the import process quick.

Unfortunately I've got a lot up in the air right now, so doing this will take a while.  Feel free to offer up a PR and I'd be happy to review it.

**Comment by CkuT** [comment]
Closed in 2e0e6bb8d2a05cbbeb6aae908b038ed34c14b746
