### ISSUE TITLE
No module named 'django'

### ISSUE THREAD

**Issue by ChristianLapinig** [danielquinn/paperless#22]
I'm trying to initialise the database, but I keep getting this error:
```
-> ./manage.py createsuperuser
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.conf import settings
ImportError: No module named 'django'
```

I installed requirements and I've changed `PASSPHRASE` in settings.py. Although I'm not sure what `CONSUMPTION_DIR` needs to be changed to

**Comment by danielquinn** [comment]
Django is a requirement for the project to work, and you install it by way of a tool called `pip`.  This is how the majority of Python projects manage dependencies.  Think of it as the Python equivalent of gem or npm, or even apt/yum/dfn/emerge.

After seeing this issue pop up though, I realised that I wrote the setup documentation with Python developers in mind, so some parts (like the requirements) aren't well defined yet.   [I've since updated the doc](http://paperless.readthedocs.org/en/latest/requirements.html) to include directions on using `pip` to install the dependencies, both from within a virtualenv, and at the user level.  I hope that helps.

As for `CONSUMPTION_DIR`, that's the directory in which Paperless will look for documents to consume.  It can be anywhere on your computer, so long as it's readable by the Paperless process and writeable by your scanner.

I hope this helps.  If you need more explanation, you can re-open this issue, and if you find the documentation lacking in parts, please feel free to issue a pull request.
