### ISSUE TITLE
Use paperless in a more general purpose (handle text files)

### ISSUE THREAD

**Issue by pawamoy** [danielquinn/paperless#223]
Hi @danielquinn , I see paperless has evolved since last time I checked, nice work :)

I'm currently searching for a way to store or index documents for a project, and paperless is surely the project that is the closest to what I have in mind.

However, and if I understand well, it only handles PDF or image files. Would it be interesting, for you and other users, to add support for text files (just copy the content in DB for search feature)? Paperless would need to recognize text files as such.

Also, maybe we could have an option to also add any type of file, even if no text can be extracted for search-feature (we would still have correspondents, title, date and tags).

**Comment by danielquinn** [comment]
Actually, after similar requests from @philippeowagner I broke up Paperless into a more modular architecture so it could handle plugins.  Now, if you want to support a file format that isn't currently supported, you just need to create a module for it and Paperless will consume that as well.

Unfortunately, I haven't documented this yet because my life is um... busy.  However, the rough details can be seen in #197 if you want to get started on your own.  I'll try to remember to write something this week, though I'm in Canada at the moment visiting family, so I make no guarantees.

**Comment by Pawamoy** [comment]
Oh indeed I saw your merged PR! Very well I'll give it a try for text files. I'll keep you in touch if I have something working. No rush for documentation, enjoy your time with your family, and thanks for your answer :)

**Comment by Pawamoy** [comment]
After a year or so, here I am again. My consumer is finally ready (to be tested), you can see the code at https://github.com/Pawamoy/paperless-text-consumer. The thing is it cannot be tested right now because the consumer loop checks for an extension in `pdf|jpe?g|png|gif|tiff?`. So the files without extension or with a `txt` extension are simply skipped:

https://github.com/danielquinn/paperless/blob/5bb90cb63dd62683154a1e110fd0d018be3b2084/src/documents/consumer.py#L85-L86

**Comment by BastianPoe** [comment]
Joe about asking all parsers whether they are able to handle the document?

If none can handle it, skip and log. If one can, than let it do its job.

**Comment by Pawamoy** [comment]
@danielquinn To test my consumer I simply renamed the files with a `.pdf` extension and gave a weight higher than 0 (my consumer handles all extensions if the file is considered a text file, with a weight of -1), but it's not ideal. Nevertheless, I'm happy to say that it's working :)

**Comment by Pawamoy** [comment]
The link to see my changes: https://github.com/danielquinn/paperless/compare/master...Pawamoy:master.

**Comment by Pawamoy** [comment]
I think what needs to be refactored is the way paperless handles HTML content types. The `file_type` document field is here only for that reason, right? To match it against the correct MIME-type? And the value of this field is computed thanks to the extension of the file.

There are a lot of MIME-types: see [this page](https://www.freeformatter.com/mime-types-list.html#mime-types-list) or [this one](https://www.sitepoint.com/mime-types-complete-list/) for "complete" lists. Not all of them would be used in paperless of course, but maybe a good portion of it. At some point, for allowing the use of custom consumers, we would need to support more of them. Currently we support the following ones:

https://github.com/danielquinn/paperless/blob/5bb90cb63dd62683154a1e110fd0d018be3b2084/src/documents/views.py#L45-L51

Two solutions comes to mind:
- hardcode them all in a data module (like `mimetypes.py`), and update that list when needed (though I have no idea how often a new MIME-type is created)
- try to fetch/guess the MIME-type based on the extension of the document file thanks to a standard/third-party library

**Comment by danielquinn** [comment]
I'm sorry I've not had a lot of time to work on this over the past few days, but here's what I have for the moment:

You're absolutely correct that the problem is in the `FileInfo` class, but I think it's not as dire as it may seem at first.  Currently, we've got a rather strict regex for `<extension>`, but [a few lines above](https://github.com/danielquinn/paperless/blob/master/src/documents/models.py#L331-L334) there's a regex we could use instead that's far more forgiving.  Maybe try swapping out the `<extension>` lines in the `REGEXES` constant with that more forgiving version and see if that solves the consumption problem?

The view on the other hand is a bigger problem because you're right: if we're going to allow for the consumption of a multitude of different file types, we need to be smarter in the view there.  The *right* way to do this would be to work backward through the process and realise that we have everything we need, just that I didn't do it right the first time around and if we fix it, it'll be ok:

Currently, we only make use of the file *name* when determining file information in the `FileInfo` class and it's all done with that Great Big Regular Expression.  However, there's no reason why [FileInfo.get_from_path()](https://github.com/danielquinn/paperless/blob/master/src/documents/models.py#L436) couldn't *also* get mimetype information using the [already-in-use](https://github.com/danielquinn/paperless/blob/master/src/documents/forms.py#L72-L73) `filemagic` module.  This mimetype could then be captured and written to the db along with the rest of the document data like `title`, `correspondent` and `extension` as part of the consumption loop.

Once we have the mimetype attached to the Document object, we can use it in the view and toss out all the stuff we currently have there mapping file extensions to hard-coded mimetypes.

Note that [documents/forms.py](https://github.com/danielquinn/paperless/blob/master/src/documents/forms.py#L16) is also using this pattern, so that would have to be patched as well.  This would essentially mean throwing out the hard-coded bits about mimetypes and rewriting line 75 to use the same logic as the consumer uses: asking the other parsers if anyone can handle the file, and if not, error out.

It looks like a lot of work, but it's not that bad really.  You up for doing it?  To be honest, I can do it, but I'm going to be slow 'cause my plate is full :-(

**Comment by Pawamoy** [comment]
Hey @danielquinn, I totally get that you don't have much time, no problem :)

Thank you for your answer, it's pretty clear and gives a wood direction towards what needs to be changed. It would be a pleasure for me to try and implements these changes but I might not be faster than you would!

Anyway, I'll think about it this coming week and see if I can start working on it soon or not :)
