### ISSUE TITLE
file extension .tif not consumed but .tiff is consumed

### ISSUE THREAD

**Issue by ayounggun** [danielquinn/paperless#232]
Hi Daniel

Thanks for the great software

If you put scan01.tif in the consumption directory, paperless doesn't consume it.

However if you rename this file to scan01.**tiff** it processes it successfully.

This is for me at least with a bare metal paperless install ubuntu 16.04.

I thought this might be a bug as both .tiff and .tif commonly used e.g. my scanner saves to .tif

Thanks

Alex

**Comment by danielquinn** [comment]
I was sure I knew where the problem was and when I went to check, I found that [the regex should be allowing for `.tif` as well as `.tiff`](https://github.com/danielquinn/paperless/blob/master/src/paperless_tesseract/signals.py#L8).  Can you confirm that you're running a `master` checkout?

If you aren't, please do a `git pull` and try again.  If you are, then this will require further tinkering and that may take some time (unless you're able to debug this yourself).

**Comment by ayounggun** [comment]
Hi Daniel

Thanks for the quick reply.

I'm afraid I can't code so wouldn't be of much help. It's not a big problem for me though so I wouldn't worry about it.

I cloned the repo in the last day or so. I looked at my signals.py and it contains

`    MATCHING_FILES = re.compile("^.*\.(pdf|jpg|gif|png|tiff?|pnm|bmp)$")` 

so I think it's bug in the current code.

Thanks

**Comment by philippeowagner** [comment]
The regex will match `tif`and `tiff` and the corresponding test case looks good for me as well.

**Comment by kskyten** [comment]
I have the same problem on the latest master. I suspect the problem might be in [models.py](https://github.com/danielquinn/paperless/blob/master/src/documents/models.py) as there are some incorrect regexes there.

**Comment by danielquinn** [comment]
Good find @kskyten.  Thanks to you, I was able to find & fix this one pretty easily.
