### ISSUE TITLE
PARSER_REGEX and PARSER_REGEX_TITLE should be case-insensitive.

### ISSUE THREAD

**Issue by blackwood** [danielquinn/paperless#24]
It took me a little while to figure out why the consumer was ignoring my PDFs, I moved them directly from my Brother DSmobile 920-DW scanner, which by default has the file extension as `.PDF`, not `.pdf`.

Thus they fail this check in the `document_consumer` script:

            if not re.match(self.PARSER_REGEX_TITLE, pdf):
                continue

**Comment by blackwood** [comment]
Alternatively solved by adding documentation about requirements for filenames?

**Comment by danielquinn** [comment]
Yeah I think I ran into this myself while I was working on a separate [feature branch](https://github.com/danielquinn/paperless/tree/feature/images-as-docs) and have fixed it there.  Since this branch will be merged into master in the next couple days, I won't be backporting the fix (there are lots of changes).

Good catch though, I'll try to merge that branch soon.

**Comment by blackwood** [comment]
Ah, roger. Thanks for the heads up!

**Comment by danielquinn** [comment]
I've merged in the new feature branch, so I'm closing this ticket now.  If you see that there's still a problem, please feel free to re-open it.
