### ISSUE TITLE
Missing CSS, when running with docker-compose

### ISSUE THREAD

**Issue by m0nhawk** [danielquinn/paperless#248]
Paperless can't found CSS, when running with `docker-compose`:

```
webserver_1  | [16/Jul/2017 14:15:50] "GET /static/admin/css/base.css HTTP/1.1" 404 99
webserver_1  | [16/Jul/2017 14:15:50] "GET /static/admin/css/dashboard.css HTTP/1.1" 404 104
webserver_1  | [16/Jul/2017 14:15:50] "GET /static/admin/css/responsive.css HTTP/1.1" 404 105
```

**Comment by danielquinn** [comment]
Maybe [this](https://github.com/danielquinn/paperless/issues/167) will help?

**Comment by dev-rke** [comment]
Hi @danielquinn

thank you for this great software.
Unfortunately the issue you referenced is still not fixed.
Could the change referenced in #167 be applied to docker-compose.yml.example?

Please add the --insecure parameter in line 20 of docker-compose.yml.example to serve CSS by default:
```patch
...
20
< command: ["runserver", "0.0.0.0:8000"]
---
> command: ["runserver", "--insecure", "0.0.0.0:8000"]
...
```

It is still not best practice, as it would be better to serve static files via nginx as suggested in #167, but i think it's better than to have an unusable docker-compose file. ;-) 

Furthermore i recommend to move the link to the documentation in the readme file upwards so that it is more visible, it took me a while to find out that i cannot use the application without creating a new user. 

Maybe it makes sense to provide some initial user setup from within the application, but this would be another ticket. :-)

**Comment by dev-rke** [comment]
I created a pull request to solve this: https://github.com/danielquinn/paperless/pull/270
