### ISSUE TITLE
Change date fields to <input type="date">

### ISSUE THREAD

**Issue by Findus23** [danielquinn/paperless#278]
I just reorganized a lot of documents and am really happy about paperless.
Just one small idea: Now that even Firefox supports using `<input type="date">` it would be nice to use it for the date boxes as it far easier to input. (Especially as I am not used to type YYYY-MM-DD format)

I think it shouldn't be a large change, but I failed to do it. I think it has to do with this line:
https://github.com/danielquinn/paperless/blob/06117929bb234cf83f322ba1ecd3614fa1c9832d/src/documents/models.py#L223

**Comment by danielquinn** [comment]
I think the problem may be that the field in question is a `DateTimeField` rather than a `DateField`.  As such, `type=date` doesn't really apply.  Now, I suppose the question is whether the *time* portion of that is even relevant for a document, and I'm not convinced that it is.  If we were to change it to a `DateField`, that may be the only thing necessary to do what you want.

Go ahead and try that, and if it works, we can have a conversation about what it would mean to strip time data from everyone else's documents, or if something more nuanced is required.

**Comment by Findus23** [comment]
Hi,

I tried replacing the `DateTimeField` with an `DateField`. (At least for me the time field is pretty useless and I'm okay with only saving the date)
This removes the time field but doesn'T solve my original issue.
![grafik](https://user-images.githubusercontent.com/6266037/34535005-cc68ebbc-f0c0-11e7-815b-7d3663be1e55.png)
The input is style `type=text"` with an JS datepicker next to it. 

I think this is intentional from django as until recently Firefox didn't support the other input types at all.
I feel like https://stackoverflow.com/questions/22846048/django-form-as-p-datefield-not-showing-input-type-as-date is the solution but I failed to implement it because I got confused by the django classes.

**Comment by danielquinn** [comment]
Ah, ok then, this is *much* easier to solve then!  We can leave the field alone as a `DateTimeField` as it renders as two separate fields anyway (I forgot that this was the norm).  Instead, we can specify a custom javascript file for the admin that just uses jQuery to override the field type.  Something like:

```javascript
jQuery("#id_created").attr("type", "date");
```

If you're familiar with Django, the way to do this is to [specify media files for the admin](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#modeladmin-asset-definitions).

This would mean that the date portion of the `created` field would be turned into a `type="date"`, while the time portion would remain the same.

So that's the *how*.  As for the *who*, well if you're so inclined, you can give that a shot and shoot me a PR when you have it working.  If you think this is beyond you, I can add it to my TODO list, but then you'll be a waiting a while.

So what do you wanna do?
