### ISSUE TITLE
API endpoint /api/documents/[id] responds with login page

### ISSUE THREAD

**Issue by chris-aeviator** [danielquinn/paperless#283]
The frontend works just fine, the api also responds correctly when fetching all documents via ``/api/documents`` whereas the endpoint ``/api/documents/1`` responds with HTML of the login page.+

Basic auth header is the same in both requests

**Comment by chris-aeviator** [comment]
when browsing the endpoint i can see, that when logged in, I'm redirected to `/admin`

**Comment by chris-aeviator** [comment]
seems like https://github.com/danielquinn/paperless/blob/3ca215e4dc3a9780b9bb0eb7c30ac6a0b606cd25/src/paperless/urls.py#L48 ( https://github.com/danielquinn/paperless/commit/f2a42ab6fe3f3c2475e357b5d37b56d441c05009) is causing this. When uncommented the api behaves correctly for me.

**Comment by danielquinn** [comment]
@chris-aeviator that line was added in the most recent release, so you're probably right in pointing to it.  For now, if anyone else is seeing this, I suggest they do as he sgguests and comment out the line if that does indeed fix the problem.

The thing is, the `/api` enpoint is defined at the top of that file and supplementary requests should never make it all wae way to the redirect as they should be captured by the endpoint definition.  I'll have to do some tinkering to see what could be wrong and will post back here when I find something.

**Comment by MasterofJOKers** [comment]
It seems, that the REST-framework only registers URLs ending with a `/` and the automatic redirect to `/` doesn't work here, because there's already a matching URL (the `RedirectView`). At least for me, going directly to `/api/documents/1` returns a redirect to `/admin/` while `/api/documents/1/` shows the document. (But I have to admit, that I'm not running the latest version and had to add the mentioned line to get that behaviour.)

**Comment by danielquinn** [comment]
Ok I've just patched this for v1.1.0.  Please let me know if things are still broken, but I think this should do the job.
