### ISSUE TITLE
Logging in paperless?

### ISSUE THREAD

**Issue by jat255** [danielquinn/paperless#29]
Probably related to #16.

It would be great to implement some sort of logging for the webserver and the consumer, since right now everything is output to stdout, it seems.  Perhaps it's just me, but I'm not sure how to capture this for later analysis. I think having some sort of log would also help with a status indicator

**Comment by danielquinn** [comment]
I completely agree.  As I've been adding new features, the need for accessible logging has become more and more obvious.  I'll get on this next.

**Comment by danielquinn** [comment]
I've added a *very* simple logger to the system now that dumps to the db rather than prints stuff out.  To access these values you can use the same admin interface that you do to see the documents.

Eventually, when I write a proper front-end, I'll use the log data in a prettier way, but for now, this is better than we once had :-)
