### ISSUE TITLE
Would ZeroDB work for storage?

### ISSUE THREAD

**Issue by waynew** [danielquinn/paperless#3]
> if someone has ideas on how to do that on encrypted data

That's a claim that [zerodb](http://www.zerodb.io/) makes. Might be something to take a look at :)

**Comment by danielquinn** [comment]
It looks like it just might actually.  There doesn't appear to be any Django support for it, but then again Django is rather over-powered for what we're trying to accomplish here.  I've been considering porting this all to a simpler Flask implementation and for that step, I bet I could get things working with ZeroDB.

I'll tinker with it when I've got some time, but note that I'm starting a new job on Monday so progress on this will be light for a while.

**Comment by danielquinn** [comment]
So I did some research on ZeroDB, and even met with the developers at a meetup here in London.  The software is pretty slick, but its Django support is non-existent.  When I asked them if they were planning Django support, they seemed surprised that this would be a thing and suggested that Pyramid support would make more sense (??).

Anyway, since this project is becoming more tightly coupled with Django, working with ZeroDB doesn't seem to be an option at the moment.  If they do introduce support for Django though, yes I'd be thrilled to switch because it does exactly what I want.
