### ISSUE TITLE
Docker: group 'paperless' in use

### ISSUE THREAD

**Issue by ChromoX** [danielquinn/paperless#306]
When attempting to start the ```danielquinn/paperless``` I get the following error message:
```
Mapping UID and GID for paperless:paperless to 1008:1008
addgroup: group 'paperless' in use
```

Any help would be greatly appreciated.

**Comment by danielquinn** [comment]
Yikes.  It looks like you've run up on a bug that only presents itself when the user running the container has a UID other than `1000`.  In your case, you've got `1008` and that's triggering [this line block of code]() that attempts to create the already-existing `paperless` group.

I'm curious as to the right methodology to follow here, so I'm going to reach out to @pitkley and @addadi on this one.  The problem is in two spots:

1. We create the `paperless` group in the Dockerfile, so creating it here doesn't make sense any more.
2. We create the group with a hard-coded id of `1000`, which wouldn't work very well for people like @ChromoX here.

The question then is whether there's a way to dynamically set the GID in the Dockerfile (I'm not sure how that'd work as it's built automatically), if we should move the user/group creation into the entrypoint, or if the entrypoint should just have some code to change the UID/GIDs -- though I'm unsure of how to do this in Alpine.

Any thoughts guys?

**Comment by ChromoX** [comment]
@danielquinn Thanks for the information. I can simply set my UID and GID to 1000 for now.

LinuxServer.io containers allow for setting the UID and GID from environment variables. Later tonight I can take a shot at integrating how they do it with paperless and issue a pull request.
