### ISSUE TITLE
Howto use MySQL as backend?

### ISSUE THREAD

**Issue by skuzzle** [danielquinn/paperless#308]
Hi,

is there an official support for the Django MySQL Backend? If so, what is the correct way to use it? I tried to override the default database in `settings.py` but when running the migrations I get an exception like 

> django.db.utils.OperationalError: 
 (1170, "BLOB/TEXT column 'content' used in key specification without a key length").

This happens while applying migrations from `0016_auto_20170325_1558`

I'm running Ubuntu within a virtual machine with Python 3.5.2, mysqlclient Version 1.3.12 and MySQL Server Version 5.7.17

I'm not really a python expert so I basically have no idea whether what I'm doing is totally stupid or maybe even kind of correct.

I do not want the database on the same virtual machine as I'm running paperless on. So I first tried to put the sqlite DB on a mounted samba share, which failed because of some bogus permission and locking issues. That is why I then tried to use MySQL as backend.

Thanks in advance, this project is awesome! I'm looking forward to have it run in production in my homenetwork!

**Comment by skuzzle** [comment]
I've just seen #183 and figured out to removed the `db_index=True` part, Migration then works fine. But from the comment https://github.com/danielquinn/paperless/issues/183#issuecomment-280863310 it seems that this should work automatically if the 'ENGINE' part contains 'mysql' which it does in my case

**Comment by danielquinn** [comment]
Hey thanks for reporting this!  You appear to have done most of the work for me, so I'll try to return the favour and get us the rest of the way there.

Basically the migration bug is still there: when we create new migrations that ask for an index on a `TextField` that MySQL can't handle, Django isn't taking that into account and is just writing `db_index=True`.  The *first* time this happened was found & fixed in #183, but it appears to have happened again with a later migration that was created recently.  *That's* the failure you're running into -- at least I think that's the case.

I've created a branch (#309) that *should* fix the problem, however since I don't use MySQL, I can't test it.  If you give it a shot and it works though, I'll merge it into `master`.

**Comment by skuzzle** [comment]
Hi there,

I've tested the migrations from the `mysql-hack` branch against an empty MySQL Database and they completed successfully! I also imported a test document to see whether everything works as expected - and it does. So for me this seems fine.

**Comment by danielquinn** [comment]
You know, I agree with you, but I'm not sure how I feel about taking on the responsibility of ensuring that Paperless works in a bunch of different databases.  I'm just one dude with a day job and 3 active side projects: [Paperless](https://github.com/danielquinn/paperless), [pyletheia](https://github.com/danielquinn/pyletheia), [Albatross](https://gitlab.com/danielquinn/albatross).  I'm trying to limit my amount of responsibility here, not expand it ;-)

So when stuff like this comes up (hopefully rarely) I'll try to troubleshoot/fix it, but I don't want to give users the impression that Paperless is ready to be deployed in a bunch of different environments that I don't use day-to-day.  The cumulative expectations would kill me.

**Comment by BastianPoe** [comment]
Sounds like a case for more unit tests to me. Those are exactly for your use case: ensuring that stuff still works after changes have been made.

**Comment by totti4ever** [comment]
So what would I have to do to try mysql?
replace `"ENGINE": "django.db.backends.postgresql_psycopg2",` in settings.py with `"ENGINE": "django.db.backends.mysql",` ?

A bit hacky on docker, but doable
