### ISSUE TITLE
Just some feedback

### ISSUE THREAD

**Issue by Pawamoy** [danielquinn/paperless#36]
Hi @danielquinn, thank you for paperless, I like it :smile: 

Here is a bit of feedback !

### About usage

Would it be possible to have a single command to launch both the admin interface and the document consumer at once? I wrote a shell script to do this but if I send one of the two in background then I can't manage the processes properly.

### Some issues

- A langdetect exception:

> Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "paperless/src/documents/management/commands/document_consumer.py", line 68, in handle
    self.loop()
  File "paperless/src/documents/management/commands/document_consumer.py", line 98, in loop
    text = self._get_ocr(pngs)
  File "paperless/src/documents/management/commands/document_consumer.py", line 161, in _get_ocr
    guessed_language = langdetect.detect(raw_text)
  File "langdetect/detector_factory.py", line 130, in detect
    return detector.detect()
  File "langdetect/detector.py", line 135, in detect
    probabilities = self.get_probabilities()
  File "langdetect/detector.py", line 142, in get_probabilities
    self._detect_block()
  File "langdetect/detector.py", line 149, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.

- Swapped sender and title:
  I noticed that the sender (an author name for example, written in the first lines of a PDF), when found, was saved as Title and that the file name was saved as Sender!

### That's it.

**Comment by danielquinn** [comment]
It'd probably be best if you submitted each of these as a separate issue, so I can respond to them properly and I can close/develop the appropriate issue.  But since you started it here, I'll try to answer them all here.

1. I don't think I'm going to write a wrapper to start both processes because that's not really a Unixy way of doing things.  One file, one job.  I have provided a `.service` file for both however, so if you're using Systemd, you can simply write your own wrapper that looks like this:

        #!/bin/sh
        systemctl start paperless-webserver.service
        systemctl start paperless-consumer.service

2. The language detection problem is hard to debug here without a sampling of the text it's failing on.  If you can, please edit the consumer to print out the text that's being passed to the language detection, and then copy/paste that text into a new issue so I can try to reproduce the bug.  Better yet, write a unit test for it :-)
3. The automatic sender/title/tag stuff is documented [here](http://paperless.readthedocs.org/en/latest/consumption.html#a-note-on-file-naming) as of last night.  If the name of the file in question was following these rules and it still came out wrong, please either (a) submit a unit test that shows the failure, or (b) post a new issue with the file name so I can test things out on my end.

I'm glad you like Paperless though!  It's turning into quite the big project, and to be honest, I'm kind of overwhelmed by the work it's generating for me!
