### ISSUE TITLE
Override webserver CSS?

### ISSUE THREAD

**Issue by SummittDweller** [danielquinn/paperless#371]
Is it possible to easily override the CSS of the webserver?  Some of the default colors are hard for me to see clearly.  I need a high-contrast display to be comfortable.

I did find the paperless.css file, added some overrides, many with !important qualifiers, and restarted my Docker containers, but the changes didn't show up.  I also rebuilt the images but still no change.

Any suggestions?  Thanks.

**Comment by SummittDweller** [comment]
Ok, I found 'custom.css' and the overrides there work once I rebuilt the webserver image.  I also found and changed the default sort order (preferred '-added' over '-created') in admin.py and that's working nicely.

**Comment by SummittDweller** [comment]
So now I see that 'paperless.css' is apparently only loaded for the 'document' and 'reminder' pages?  Was it intentionally omitted from the other pages?  I don't understand the structure of the code well enough to know where/how to add it to the other pages.  Any suggestions?

The applicable block of code appears to be ...

    class Media:
        css = {
            "all": ("paperless.css",)
        }

**Comment by danielquinn** [comment]
Sorry it's taken me so long to get back to you on this.  I've been working on getting my visa in this country worked out.

There's currently no "global" CSS changes because they hadn't been requested yet, but your use case is as good a reason as any to have one, so I just added this feature to the `master` branch.  To make use of it, do a `git pull`, add a file called `overrides.css` to the root of your media directory, and restart the Paperless webserver.  Anything you put in there will affect the entire site.

**Comment by danielquinn** [comment]
I'm going to close this issue now, but if you think we can do more for this use case, just re-open it and let me know.

**Comment by SummittDweller** [comment]
Thanks Daniel and best wishes on the visa.  I have a week off to work on things like this so I'll give it a try in the next day or two.  I don't anticipate needing anything more related to this but if something comes up I'll post here.  Take care.
