### ISSUE TITLE
How About Celery for do the hard work?

### ISSUE THREAD

**Issue by alexandreferreira** [danielquinn/paperless#41]
Hey,

I used celery for long and hard task using workers in some projects, do you guys think that will fit well in this project?

http://www.celeryproject.org/

**Comment by danielquinn** [comment]
Celery is great.  I've used it myself for a number of projects, but for this case, since we have a dedicated worker working off of a directory queue, I don't see any value in introducing it at this point.  I suppose that if at some point we wanted to rewrite the consumer to be event-based or something, (rather than just operating in a loop as it does currently) we might tap celery, but at present, the "event" in question is always going to be the presence of a file in the consumption directory (as placed there by the scanner) so you're not winning anything by switching from a directory-checking loop to an event-based model.
