### ISSUE TITLE
cache thumbnails in browser

### ISSUE THREAD

**Issue by Findus23** [danielquinn/paperless#411]
related to #410 

Another way to massively speedup the page load (after the first time) would be to cache the thumbnails and only load them when they changed (via etag or something like this).

Now that I think about it, thumbnails should normally never change so running it behind behind nginx and adding a cache header for `/fetch/thumb/` should maybe also be enough.

**Comment by MasterofJOKers** [comment]
+1 for this, because using paperless over a slow connection (when not at home via VPN) is a real pain with thumbnails are reloaded every time.

I've got some changes for this, but they're probably not clean enough for a pull-request, so I just leave them here as a hint what might be done:
```diff
diff --git a/src/documents/views.py b/src/documents/views.py
index e297e09..b4146be 100644
--- a/src/documents/views.py
+++ b/src/documents/views.py
@@ -1,6 +1,7 @@
 from django.http import HttpResponse, HttpResponseBadRequest
 from django.views.generic import DetailView, FormView, TemplateView
 from django_filters.rest_framework import DjangoFilterBackend
+from django.utils.cache import patch_response_headers
 from paperless.db import GnuPG
 from paperless.mixins import SessionOrBasicAuthMixin
 from paperless.views import StandardPagination
@@ -51,10 +52,12 @@ class FetchView(SessionOrBasicAuthMixin, DetailView):
         }
 
         if self.kwargs["kind"] == "thumb":
-            return HttpResponse(
+            response = HttpResponse(
                 self._get_raw_data(self.object.thumbnail_file),
                 content_type=content_types[Document.TYPE_PNG]
             )
+            patch_response_headers(response)
+            return response
 
         response = HttpResponse(
             self._get_raw_data(self.object.source_file),
diff --git a/src/paperless/settings.py b/src/paperless/settings.py
index 06cc180..833a316 100644
--- a/src/paperless/settings.py
+++ b/src/paperless/settings.py
@@ -280,3 +280,5 @@ FY_END = os.getenv("PAPERLESS_FINANCIAL_YEAR_END")
 
 # Specify the default date order (for autodetected dates)
 DATE_ORDER = os.getenv("PAPERLESS_DATE_ORDER", "DMY")
+
+CACHE_MIDDLEWARE_SECONDS = 3600
```

My main concern is with setting the `CACHE_MIDDLEWARE_SECONDS` here, as I'd like that to be a little higher than the default 600. Also https://docs.djangoproject.com/en/2.0/ref/utils/#django.utils.cache.patch_response_headers for reference to `patch_response_headers`.

**Comment by jonaswinkler** [comment]
You may also consider to add the ConditionalGetMiddleware, like so:

`
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
`

This will add ETag headers to all objects returned by django, including the thumbnails. Your browser will store these tags, send them with every request, and django will happily respond with 304 Not Modified, should the ETag of an object still match.

However, this may also affect other parts of paperless and cause issues...? (unsure)

**Comment by danielquinn** [comment]
@MasterofJOKers, it looks like we can pass whatever value we like to `patch_response_headers()` without having to modify the `CACHE_MIDDLEWARE_SECONDS` value.  For these thumbnails, I think a crazy-big value like `31536000` (1year) may even be appropriate since there's no way that these thumbnails will change.

So, we could reasonably do something like this, no?

```python
from django.utils.cache import patch_response_headers

...

response = HttpResponse(
    self._get_raw_data(self.object.thumbnail_file),
    content_type=content_types[Document.TYPE_PNG]
)
patch_response_headers(response, cache_timeout=60*60*24*365)
return response
```

@jonaswinkler I've never fiddled with Etags in Django, but am I right in assuming that all I'd have to do is inject `django.middleware.http.ConditionalGetMiddleware` into `MIDDLEWARE` and Django does the rest?  Would this conflict or cause any problems with the above use of `patch_response_headers()`?  Are both even necessary, or should we just use one?
