### ISSUE TITLE
Backup papierless

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#428]
I am using paperless now since a year. Great application!
Is there a way to securely backup my documents? Is it enough and safe to copy the whole paperless folder to an external harddisk?
How do you backup your documents/paperless?

Best regard,
   Ulli

**Comment by danielquinn** [comment]
If you're not using encryption, making a copy of your `documents/originals` directory should be enough, but that will only get you the original documents and not the indexing results, tagging etc.  If you want all of that, you probably want to d a proper export.  [Have a look at the documentation](https://paperless.readthedocs.io/en/latest/utilities.html#utilities-exporter) for how to do that.

Hope that helps :-)

**Comment by ddddavidmartin** [comment]
Great question! I have always wondered how other people backed up their files. I'm not too familiar with databases and things, but what I have heard is that you are not meant to back up database files directly. They can be locked or in progress with something and it can lead to a broken database in the backup. AFAIK you are meant to extract it and basically back it up as a text file, and then put it back together from the backup. It is on my list but I never got around to look into it further.

I have my Paperless files backed up to the cloud with [Tresorit](https://tresorit.com/). It's a bit more expensive than Dropbox or Google Drive but end-to-end encrypted which matters to me for my documents. This also syncs them to my laptop so that I always have a local copy and one in the cloud.

Below is the shell script I use to back up Paperless. It runs nightly from a cron job. It stops Paperless to avoid issues with the database file being locked. Rsync helps by being incremental and it only copies the files that changed.
```
#!/bin/sh

# Stop, back up and start paperless again.

echo "Stopping paperless"
systemctl stop paperless-webserver
systemctl stop paperless-consumer
sleep 2s

rsync --archive --verbose --delete /home/littlebig/Documents/paperless/ /home/littlebig/Documents/paperless_backup

echo "Starting paperless"
systemctl start paperless-webserver
systemctl start paperless-consumer
```

The `paperless_backup` directory is tracked by the cloud backup and basically not touched by anything else.
