### ISSUE TITLE
convert does not work with ImageMagick 7.x

### ISSUE THREAD

**Issue by jat255** [danielquinn/paperless#439]
Error when attempting to convert a document:

```
convert: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
```

Found [this](https://github.com/ImageMagick/ImageMagick/issues/1310) issue and [this](https://bugs.archlinux.org/task/60580) bug report on the Arch tracker. Apparently there is a security issue in converting to/from pdf so it is disabled (or beginning to be) in many distributions.

**Comment by jat255** [comment]
Apparently, the solution is to manually patch ImageMagick's `policy.xml` file. This can be done at the system level, or can be done for the user individually in the `$HOME/.config/ImageMagick/` folder (at least on my system). 

Running `convert -debug configure logo: null: ` will show you where the `policy.xml` file can be placed. On my system, this was the folder above. I changed line 72 from `<policy domain="coder" rights="none" pattern="{PS,PS2,PS3,EPS,PDF,XPS}" />` to `<policy domain="coder" rights="all" pattern="{PS,PS2,PS3,EPS,PDF,XPS}" />` and it worked again...

Although if this is a security issue as the maintainers think, then maybe we should rethink how this is done.

**Comment by danielquinn** [comment]
From what I understand, this was due to a security issue in ghostscript which ImageMagick preemptively blacklisted as a safety measure.  From what I last heard, said security issue has been solved, so future versions of ImageMagick shouldn't have this restriction (hopefully).

As your issue is solved though, I'm going to close this now.
