### ISSUE TITLE
case of document.contents for document_retagger, etc.

### ISSUE THREAD

**Issue by darkermatter** [danielquinn/paperless#45]
Hi Daniel!

It appears that the document contents are stored in mixed case but all tags are stored and matched in lower case. Shouldn't the contents be stored as lower case?

I love this project!!! I'm moving all my PDF files into it. At the moment I only have about 1500 in there and things seem to be running okay. I wonder how many will make sqlite start to crack.

**Comment by danielquinn** [comment]
It's true, the matching is done assuming all lower case, but that's because `Document.content` is modified with `.lower()` just before the match step.  This way we get to preserve the original content and still match in a case insensitive way :-)

I'm glad you like the project though!  I had no idea it would be so popular when I first released it.

**Comment by darkermatter** [comment]
Hi Daniel,

I think you should move the .lower() call into tag.matches so it will work in all situations. document_retagger doesn't work properly as there is no .lower() in the management command.

**Comment by danielquinn** [comment]
Excellent point.  Actually, I thought I'd written it that way from the beginning!  Thanks, I'll make that adjustment and close this when it's done.

**Comment by danielquinn** [comment]
Thanks for finding that.  I introduced `.match_all()` which returns a generator yielding matching tags.
