### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by avichalp** [danielquinn/paperless#6]
What do guys think about implementing a full text search ? It would be very helpful if one can search through all the stored bills/receipts? How about using elasticsearch ?

**Comment by danielquinn** [comment]
To be honest, I thought that sqlite was already doing that.  I do a search and it finds words deep in the body of the `content` field, so I assume that everything's working as it should.

I'm resistant to the idea of implementing ElasticSearch though because this is a small project designed for a small amount of data.  I can't think of a case where you'd need anything more impressive than a simple database to search all of the stuff that would ever need to go in there.  There's no multi-user required, and performance on a small data set isn't really a problem.  In other words, ES is an additional moving part in a system that should be easy so I'm not thrilled about including it.

With that said though, if you can send me a pull request that can make it work *without* ElasticSearch as well as with it, then I'd merge it happily.  But if you're asking me if I have any plans to personally do that work, that'd be a no.

**Comment by avichalp** [comment]
Elasticsearch would become an additional moving part also there would be an operational overhead of maintaining elasticsearch server. I think sqllite should suffice here.
