### ISSUE TITLE
Make Logging Suck Less

### ISSUE THREAD

**Issue by danielquinn** [danielquinn/paperless#60]
The logging facility I introduced in #16 is crude and doesn't make use of Python's native logging.  I did this because I find Python's native logging facility confusing, but I hear that it can do what I want.

So, here's what I think logging should do:

* You should be able to call it at arbitrary times, giving each message a level like `debug`, `error`, `warning`, etc.
* You should be able to watch the logging output in a stream, like `tail -f /path/to/file`
* You should be able to do REST API calls to get something like "the last 5 messages of level `>=info`".

The problem for me is that I can't figure out how to solve logging and still allow for the second and third point above.  Any advice on this is greatly appreciated.

**Comment by the01** [comment]
I have some limited experience with logging, so here is how I see it:
- simply use `logging.debug()`, `logging.error()`, `logging.warning()` etc. (or rather loggers)
- The easiest way would be to setup logging to a [file](https://docs.python.org/3/howto/logging.html#logging-to-a-file)
- The logging module has the concept of [handlers](https://docs.python.org/3/library/logging.handlers.html) which are responsible for logging to a target. (e.g. there are already handlers for logging to streams, files or even the network builtin). We would need to use (write) a handler that logs to a database. A quick search shows that has already been done for sqlite. So that shouldn't be a big problem.
The api call would then just be a db query.

A bit of self-promotion, but maybe it's something you find useful: I have written some code that lets you simplify the logging process (especially in object oriented programming). For example inheriting classes can use `self.debug()`/`self.info()`,... and the class is the logger name (optionally an id). It can also add the function name where the log statement was called from.
The package is called [flotils](https://github.com/the01/python-flotils) (not very creative on my part) and a detailed example is in the [docs](https://github.com/the01/python-flotils/blob/master/docs/logable.adoc)
[end of self promo]

**Comment by danielquinn** [comment]
Well I'm feeling like death today, but later this week I'll take a look at these links and work something out.  Thanks for the input!

**Comment by danielquinn** [comment]
I've now totally overhauled the logging system, making proper use of the Python's logging module.

**Comment by stueja** [comment]
Hi,
is it possbile to turn the logging of served thumbnails off? Loading the "Documents" page causes a lot of logging messages like
```
Jan 22 11:45:51 brick python[466]: [22/Jan/2019 11:45:51] "GET /fetch/thumb/311 HTTP/1.0" 200 42941
```
Thanks,
Jan

**Comment by danielquinn** [comment]
Not that I know of.  The thumbnails (and documents) are all served *through* Django to maintain security and handle decryption (if enabled).  The files can't be accessed without going through the Paperless/Django server, and so they get logged.

You might be able to fiddle with [Django's `LOGGING` variable in settings.py](https://docs.djangoproject.com/en/2.1/topics/logging/), but I wouldn't know how to do it off-hand.  If you figure it out though, feel free to add some documentation to the project :-)
