### ISSUE TITLE
How does one change document naming after it's consumed?

### ISSUE THREAD

**Issue by wsuff** [danielquinn/paperless#63]
Unfortunately the muti function I will be using for a bulk of my documents due to ADF is rather silly in it's  Scan to FTP options. Static prefix + document counter . pdf.  I saw the documentation on the retagging which would apply here [as docs increase I'll need to add tags for organization] It appears I can change the Sender / File name from the web ui as well but with volume that might be rather painful and was hoping I missed something or there are other suggestions. Granted this won't be as much of an issue if I was to scan documents as they come in but since I'm testing how things work I have a backlog [file cabinet full] that I'd like to digitize just to have access to them.

I'm considered a pre consumer step to name the files better first but I am trying to come to a solution that limits the manual work required. OCR text may be enough to identify repetitive things [utility bill etc].
It would be prefer to not have to manually rename every file consumed.

**Comment by danielquinn** [comment]
I think you're misunderstanding the whole file-naming thing, so I'll try to explain.  If it turns out that it's me that's missing something, please set me right.

The name of the file only comes into play at two points in time:

* During consumption, the consumer tries to guess the sender, title, and tags based on the file name.  If the name matches the expected pattern, the database is updated with these values.
* During Export, the files are saved to an empty directory and named according to the same convention used during import.

Importantly, Paperless only really operates *between* those two stages.  That is to say, if you import a document called MyPrefix123.pdf, it'll do the following:

* OCR the document and put the text into the database with the following metadata:
    * Title: `MyPrefix123`
    * File Type: `pdf`
    * Sender: `None`
    * Tags: *assigned based on the auto-tagging rules you define in the admin interface*
* Encrypt the file and save it to the `media/documents/` directory using the primary key as the file name, so the stored file will look like this: `media/documents/0000156.pdf.gpg`.

There's currently no logic in Paperless that would allow it to guess the sender and title based on the contents of the document and frankly, I wouldn't know where to start to make that happen.  So, if you're doing a mass-import, I'd recommend trying to do what you can with the file names before the import rather than trying to use the admin to change them all after they've been imported.

I've been considering some form of a bulk-editing feature.  Something that'd let you assign a sender, title, or tag to a group of documents, but that's a way's off, since it'd be part of the new UI.

Another solution might be to use the same logic I've got on the tags, and apply it to senders: allow users to define matching algorithms (if document contains the word 'T-Mobile', set sender='T-Mobile'), so that might help you get part-way there, but this wouldn't solve the title problem, since in most cases, while you may have many documents with the same sender, you're unlikely to have the same happen with titles.

So does that help at all?

**Comment by wsuff** [comment]
Wow. Thanks for the in-depth response. It reconfirms what I expected that I'll need to name files prior to document consumption if at all possible. 

Very well said to be honest. Paperless was easy to get setup with the Scan to FTP directly but I guess I overlooked that there was no easy way to name the files with some intervention or additional steps.

Glad I asked tho since it helped understand how it's used and potential solutions.
