### ISSUE TITLE
Which NAS would you recommend?

### ISSUE THREAD

**Issue by lherich** [danielquinn/paperless#64]
Thank you for this awesome project! I am asking here, because there exists no support forum etc. for paperless. I hope my issue does not interfere too much.

I am thinking about buying a NAS with RAID 1 for paperless. However I am not really into running custom code on a NAS nor I have a NAS. 
So I want to ask, if someone has paperless running on his NAS and/or could recommend a simple NAS for paperless with two HDDs (RAID 1). :)

Thanks a lot.

**Comment by danielquinn** [comment]
It's no problem asking here, though there is a gitter chat if you're into that.

Anyway, in answer to your question, I'm afraid I don't have much advice on a NAS other than (a) you don't need anything nearly that big unless you're scanning *tens of thousands of documents*, and (b) since Paperless requires that you have Python 3, Tesseract, and ImageMagick installed on the host system, I'm going to go out on a limb and assume that most NAS devices don't have all three of those.

I've got a Synology in my home, but I didn't install Paperless on it because of the above.  It can do Python 3, but there's no point-and-click way to install either Tesseract or ImageMagick.  Instead, I've got a little [Intel NUC](https://en.wikipedia.org/wiki/Next_Unit_of_Computing) (super cheap one, spinner hard disk, Celeron CPU) running [Gentoo](https://gentoo.org/) and doing all of the work.  I use my Synology primarily as a Great Big Disk and that's about it.

I have been toying with the idea of offering Paperless as a physical device: a RasberryPi or something similar with Paperless pre-installed, but that's only if it looks like there'd be a market for it.

I hope this answers your question, but if you need to expand on it, feel free to re-open this issue.
