### ISSUE TITLE
Not consuming on Vagrant

### ISSUE THREAD

**Issue by plaindocs** [danielquinn/paperless#75]
I'm testing this locally on Linux, and can't seem to get consumption to work. Django runs fine, consumer lists no errors, I have a PDF in the consumption dir. 

Nothing. 

Any gotchas? File size, type? Anything else?

**Comment by danielquinn** [comment]
The consumer is pretty simple, it looks for anything named `*.pdf`, `*.jpg`, `*.gif`, `*.png` in the consumption dir and then tries to import it.  If it finds one and can't import it, you'll see an error message in the output (and the database log).  So if you're not getting *any* output, it's probably because Paperless is looking in the wrong place?

Remember that in the case of the Vagrant setup, **the consumption dir must be visible from inside the VM** since that's where the Paperless consumer is operating.  In the past I've seen people set `PAPERLESS_CONSUMPTION_DIR` to something like `/tmp/paperless` and then put the files there on the *host* machine rather than the guest (the VM).  This might be your situation.

You're not the first person to run into this, so I'm going to add a little debugging output to the consumer start sequence that declares where it's looking to help with debugging.  Gimme a few minutes and I'll let you know when it's ready.  Then you can do a `git pull` and try again to see what happens.

**Comment by plaindocs** [comment]
Woah, amazingly quick response. Thanks :-)

Embarrassingly, it looks like I could have put a faulty PDF in there, I double checked the Vagrant mount point and copied another over and it seems fine.
