### ISSUE TITLE
docker-compose image library/paperless not found

### ISSUE THREAD

**Issue by skydge** [danielquinn/paperless#84]
Hi Daniel,
Thank you for this awesome project.
I tried to setup Paperless with docker and found an issue with the docker-compose.yml file.

$ docker-compose up
Creating volume "paperless_media" with default driver
Creating volume "paperless_data" with default driver
Recreating paperless_webserver_1
Pulling webserver (paperless:latest)...
Pulling repository docker.io/library/paperless
ERROR: Error: image library/paperless not found

The image is not found with the sample YML provided.
I changed both "image:" in the YML file for the one I found on Docker Hub:
pitkley/paperless
And it worked.

My setup is fresh Ubuntu Server:
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

With official docker repository:
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

$ docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

Paperless is now working and I can access the webserver.
I'm not able to consume a PDF at the moment, it shows Consuming+Generating in the Logs, but nothing appends after that. I'm still troubleshooting my setup - anyway this is not related to this issue.

Again thank you for sharing your work.
Best regards,
David

**Comment by danielquinn** [comment]
I'm not sure how that happened, but it looks like the original file, which referenced `pitkley/paperless` was changed to just `paperless` -- probably when we were fiddling with using `.example` files instead of checking in the `.yml` files directly.

I've fixed the file to reference `pitkley/paperless` again, but at some point this is likely to change to `danielquinn/paperless` once I get the hang of using Docker Hub.  For now though, thanks for finding this and reporting it!
