### ISSUE TITLE
Visible thumbnails without downloading whole file? 

### ISSUE THREAD

**Issue by ralesi** [danielquinn/paperless#87]
I notice the document consumer creates a thumbnail,  but I do not see it used in the web interface.   Is there something I am missing or is this functionality currently not used?

**Comment by danielquinn** [comment]
Nope, it's not just you.  Currently, the "UI" is just the automatically-generated admin interface provided by Django (the underlying web framework) out of the box.  There's a volunteer working on a proper UI which is written using Angular and based on the API underneath.  I've added the thumbnail support in anticipation of this new UI so that they might be used there :-)

**Comment by Ulli2k** [comment]
can a preview be used? is it stable enough?

**Comment by danielquinn** [comment]
The volunteer that was working on the UI seems to have disappeared as I never received a PR from them.  I have [one of my own](https://github.com/danielquinn/paperless/tree/ui) that I'm fiddling with, but it's nowhere near production-ready at this stage.  The thumbnail image however should be ready for use whenever you like.

**Comment by Ulli2k** [comment]
oh, thats not good...
the one you are working on....can I give it a try (I would expect the current functionality which comes from django and is currently available is still running just the new parts are not stabile?)

your link directs me to the root tree...where can I find your stuff?

**Comment by danielquinn** [comment]
That's the right link.  It's just a separate branch.  You'd have to checkout out the `ui` branch from this repo and then try to use it locally.  It's not even close to ready though, so there are missing components and the js is buggy as shit.  You're welcome to fiddle though and send a PR if you like ;-)
