### ISSUE TITLE
Question: Upload options besides Scan-to-FTP

### ISSUE THREAD

**Issue by MatthiasKauer** [danielquinn/paperless#91]
Hi,
this project looks awesome and I'd like to make it work for me.

Now, I'm wondering about the workflow.
The readme states that I need to scan to FTP. This is convenient, but are there are any alternatives if your scanner doesn't support that?

Can I upload pdf documents via FTP from my computer? Is there a web UI where I can upload pdf documents?
I also keep reading about the API in other issues: Did I understand correctly that I can upload pdf files over that if I write the corresponding script?

Maybe this deserves another sentence in the "How it works" section in the readme.

Thanks for making this!
Matthias

**Comment by danielquinn** [comment]
Paperless isn't picky about how it receives files to consume.  It just monitors a directory for new files and then consumes what it finds there.  FTP is mentioned in the README because that's a common feature for these network-based scanners, but SMB (Windows file sharing) would work just as well, as would manually copying a PDF into the consumption directory yourself.  I know of one user whose scanner writes to a local USB stick, which he then pulls out of the scanner, inserts into the Linux box running Paperless, and then copies the file from there.  Certainly not ideal, but it works.

Regarding the API, yes you can indeed do that, though it's probably more difficult than any of the other options mentioned above.  Document submission via the API currently makes use of a "shared secret" for security (some people are putting Paperless on the open internet), so you'd have to implement support for that in order to use it.  The instructions for this are all documented though, so if that's what you want, it's not that difficult.

I've since added a bit to the README to hopefully clarify things a bit, so I'm closing this, but if you think the README needs more, just re-open it.

**Comment by stringlytyped** [comment]
I'd also like to point out that many scanners nowadays support uploading to cloud services like Dropbox or Google Drive. Dropbox, in particular, has a [headless version](https://www.dropbox.com/install?os=lnx) you can install on your Paperless server. So, you could use that along with Dropbox's selective sync feature to get your PDFs to Paperless (just be sure to point your consumption directory path to the appropriate Dropbox folder).

I personally use an AppleScript (I use Macs at home—I am sure something similar could be constructed for Windows or Linux) that uploads any files sent to it to my FTP server, running on my Paperless box. I have configured the software that comes with my scanner (it's not a network scanner) to send files to that AppleScript. So my workflow is to 1) scan a document and 2) click the "Send to Paperless" button in my scanner software.

The software that manufacturers bundle with their scanners are almost always capable of sending files to a program on your computer, so this is a great option if you don't have a network scanner. Or, if you don't want to use your scanner's software, the Image Capture app will let you do the same thing, if you are on a Mac.

**Comment by MatthiasKauer** [comment]
This is all awesome!
Thank you so much.
