### ISSUE TITLE
Updating paperless from git master

### ISSUE THREAD

**Issue by polo2ro** [danielquinn/paperless#92]
Hi,
i have paperless running on a personal server for while now. I have figured out i would be better to update the code to get the last features from the master branch. This is troublesome because the settings.py file get in the way. Is there a possibility to move this file in another location? example : /etc/paperless/settings.py or something like that.

```
~/git/paperless$ git pull
remote: Counting objects: 474, done.
remote: Total 474 (delta 121), reused 121 (delta 121), pack-reused 353
Réception d'objets: 100% (474/474), 89.63 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (310/310), complété avec 45 objets locaux.
Depuis https://github.com/pitkley/paperless
   1e7ece8..f7e96ea  master     -> origin/master
 + 07301ab...13571f5 fix/documentation -> origin/fix/documentation  (mise à jour forcée)
Mise à jour 1e7ece8..f7e96ea
error: Your local changes to the following files would be overwritten by merge:
	src/paperless/settings.py
Please, commit your changes or stash them before you can merge.
Aborting
```

Thanks for this software, very useful to me

**Comment by danielquinn** [comment]
I'm happy to see it's working for you!

When I first started Paperless, the instructions were to edit `settings.py` to set the appropriate variables, but I've since removed all need to modify that file, instead using environment variables and/or `/etc/paperless.conf`.  If you've still got changes in that file, can I ask what they are?  If you're adding/changing stuff other than variable values, then maybe I need to look into something pluggable.

If you're only editing the various Paperless-specific variable values, then I'd suggest you take a look at the [paperless.conf.example](https://github.com/danielquinn/paperless/blob/master/paperless.conf.example) file, copy it to `/etc/paperless.conf` and edit it to suit your needs, then just `git checkout src/paperless/settings.py` so you never have to worry about this file again.

**Comment by danielquinn** [comment]
I just took a look at [the setup page](http://paperless.readthedocs.org/en/latest/setup.html) and I hadn't realised that there was still some documentation that encouraged editing `settings.py`.  I'm sorry about that, and I've just now fixed it to encourage the explanation I've given here.  If that's enough to solve your problem, please just close this issue, otherwise, let me know if there's something else I can do.

**Comment by polo2ro** [comment]
Thanks for all the informations, i created the new file and all works well. I had to install the new dependencies and run the migrate script to fix all the problems
